language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer --prefer-source --dev install

script: phpunit --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - php: hhvm
